apiVersion: v1
entries:
  camel-dashboard-console:
  - apiVersion: v2
    appVersion: 0.3.1
    created: "2026-01-14T17:13:22.723020161Z"
    description: A Helm chart for installing the Camel Dashboard OpenShift Console
      plugin
    digest: 2f6ee3aae0607cc92678145a691d486512b3c45d4c898c2babb74e3f9f1c7135
    keywords:
    - camel
    - dashboard
    - console
    - react
    name: camel-dashboard-console
    sources:
    - https://github.com/camel-tooling/camel-dashboard-console.git
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-console-0.3.1.tgz
    version: 0.3.1
  - apiVersion: v2
    appVersion: 0.3.0
    created: "2026-01-12T15:02:35.860341007Z"
    description: A Helm chart for installing the Camel Dashboard OpenShift Console
      plugin
    digest: da2d9ce4344d7396bcf5fb75b298b60335bcb2adf6afc53bdfaa0480c173bbdb
    keywords:
    - camel
    - dashboard
    - console
    - react
    name: camel-dashboard-console
    sources:
    - https://github.com/camel-tooling/camel-dashboard-console.git
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-console-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 0.2.2
    created: "2025-11-19T14:36:08.748891845Z"
    description: A Helm chart for installing the Camel Dashboard OpenShift Console
      plugin
    digest: b67497ac14002283678ab2a1e9afabecc3f07237c8625b8d9362c24f6e50cd67
    keywords:
    - camel
    - dashboard
    - console
    - react
    name: camel-dashboard-console
    sources:
    - https://github.com/camel-tooling/camel-dashboard-console.git
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-console-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2025-10-17T15:26:22.846868951Z"
    description: A Helm chart for installing the Camel Dashboard OpenShift Console
      plugin
    digest: bbb3923780e7167d038325bed33db627185aaed2cd6d0dc3c5a965876cfeb3c6
    keywords:
    - camel
    - dashboard
    - console
    - react
    name: camel-dashboard-console
    sources:
    - https://github.com/camel-tooling/camel-dashboard-console.git
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-console-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2025-09-19T12:40:55.922648756Z"
    description: A Helm chart for installing the Camel Dashboard OpenShift Console
      plugin
    digest: bf7edf71a326a0d2fc2db1869456b25ae328adfa77f2a70e622a8c74bbb8d29b
    keywords:
    - camel
    - dashboard
    - console
    - react
    name: camel-dashboard-console
    sources:
    - https://github.com/camel-tooling/camel-dashboard-console.git
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-console-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-09-19T12:03:27.957385086Z"
    description: A Helm chart for installing the Camel Dashboard OpenShift Console
      plugin
    digest: 077a98049d3804a9d7b571f8fecefc49ab47ed08ebc43f6990d76bb939c67221
    keywords:
    - camel
    - dashboard
    - console
    - react
    name: camel-dashboard-console
    sources:
    - https://github.com/camel-tooling/camel-dashboard-console.git
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-console-0.1.0.tgz
    version: 0.1.0
  camel-dashboard-openshift-all:
  - apiVersion: v2
    created: "2026-02-05T11:04:59.764418012Z"
    dependencies:
    - condition: camel-dashboard-operator.enabled
      name: camel-dashboard-operator
      repository: https://camel-tooling.github.io/camel-dashboard/charts
      version: 0.1.0
    - condition: camel-dashboard-console.enabled
      name: camel-dashboard-console
      repository: https://camel-tooling.github.io/camel-dashboard/charts
      version: 0.3.1
    - condition: hawtio-online-console-plugin.enabled
      name: hawtio-online-console-plugin
      repository: https://hawtio.github.io/hawtio-charts
      version: 0.6.2
    description: Helm umbrella chart for Camel Dashboard on OpenShift
    digest: 7912442440d3da68945a82879d2fc8df92a5531576d62af1745eb109b3862fae
    home: https://camel-tooling.github.io/camel-dashboard/
    icon: https://raw.githubusercontent.com/camel-tooling/camel-dashboard-openshift-all/refs/heads/main/icons/logo.png
    keywords:
    - camel
    - dashboard
    - operator
    - console
    - integration
    - hawtio
    - jolokia
    - jmx
    - openshift
    kubeVersion: '>= 1.33'
    maintainers:
    - email: gfournier@apache.org
      name: gfournier
    name: camel-dashboard-openshift-all
    sources:
    - https://github.com/camel-tooling/camel-dashboard
    - https://github.com/camel-tooling/camel-dashboard-operator
    - https://github.com/camel-tooling/camel-dashboard-console
    - https://github.com/hawtio/hawtio-online
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-openshift-all-4.20.0.tgz
    version: 4.20.0
  - apiVersion: v2
    created: "2026-02-05T09:31:55.970307003Z"
    dependencies:
    - condition: camel-dashboard-operator.enabled
      name: camel-dashboard-operator
      repository: https://camel-tooling.github.io/camel-dashboard/charts
      version: 0.1.0
    - condition: camel-dashboard-console.enabled
      name: camel-dashboard-console
      repository: https://camel-tooling.github.io/camel-dashboard/charts
      version: 0.2.2
    - condition: hawtio-online-console-plugin.enabled
      name: hawtio-online-console-plugin
      repository: https://hawtio.github.io/hawtio-charts
      version: 0.6.2
    description: Helm umbrella chart for Camel Dashboard on OpenShift
    digest: 51be62a4e59a9c493b43d6bf763e34214dbda977a99ea3c9c845eaacc1f23537
    home: https://camel-tooling.github.io/camel-dashboard/
    icon: https://raw.githubusercontent.com/camel-tooling/camel-dashboard-openshift-all/refs/heads/main/icons/logo.png
    keywords:
    - camel
    - dashboard
    - operator
    - console
    - integration
    - hawtio
    - jolokia
    - jmx
    - openshift
    kubeVersion: '>= 1.32'
    maintainers:
    - email: gfournier@apache.org
      name: gfournier
    name: camel-dashboard-openshift-all
    sources:
    - https://github.com/camel-tooling/camel-dashboard
    - https://github.com/camel-tooling/camel-dashboard-operator
    - https://github.com/camel-tooling/camel-dashboard-console
    - https://github.com/hawtio/hawtio-online
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-openshift-all-4.19.0.tgz
    version: 4.19.0
  camel-dashboard-operator:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-09-23T11:57:27.264648395+02:00"
    description: TODO
    digest: a61239288c7e7581cfb0ccbe534dac25fa8d1d0d0e0c30011ad8a4681b64401c
    home: https://camel.apache.org/camel/latest/
    icon: https://github.com/apache/camel/raw/main/docs/img/logo64-d.png
    keywords:
    - integration
    - camel
    - dashboard
    maintainers:
    - email: pcongiusti@apache.org
      name: pcongiusti
    name: camel-dashboard-operator
    sources:
    - https://github.com/camel-tooling/camel-dashboard-operator
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-operator-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2025-09-23T11:54:55.812983717+02:00"
    description: TODO
    digest: de0ac6935873a2bea309ea4fdaab5ce478fe66dfdc766aaedc1bdc8ce68fd1a5
    home: https://camel.apache.org/camel/latest/
    icon: https://github.com/apache/camel/raw/main/docs/img/logo64-d.png
    keywords:
    - integration
    - camel
    - dashboard
    maintainers:
    - email: pcongiusti@apache.org
      name: pcongiusti
    name: camel-dashboard-operator
    sources:
    - https://github.com/camel-tooling/camel-dashboard-operator
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-operator-0.0.1.tgz
    version: 0.0.1
generated: "2026-02-05T11:04:59.760568796Z"
